import os
import sys
import json
import datetime
import tkinter as tk
from tkinter import messagebox
import time
import openpyxl
from openpyxl.drawing.image import Image as ExcelImage
import threading
import queue
import urllib.parse
from urllib.parse import urlparse, parse_qs
import re

def analyze_and_generate_code(elements_data, output_dir):
    if not elements_data:
        return
        
    print("--- 抽出ロジックの解析とコード生成開始 ---")
    
    # 1. ページ遷移後の共通アンカーの特定
    wait_anchor_xpath = elements_data[0]['xpath'] if len(elements_data) > 0 else "body"
        
    # 2. Pager-Next (次へボタン) の特定
    next_btn = None
    next_btn_memo = ["次", "next", "->", "＞", ">"]
    for el in reversed(elements_data):
        memo = el.get("memo", "").lower()
        if any(m in memo for m in next_btn_memo) or any(m in el["text"].lower() for m in next_btn_memo):
            next_btn = el
            break
            
    # 3. URL戦略判定
    strategy = "PHYSICAL_CLICK"
    base_url = elements_data[0]['url']
    pages_urls = list({el['url']: True for el in elements_data}.keys()) # unique URLs preserving order
    dynamic_param_key = None
    start_page_val = 1
    
    if len(pages_urls) > 1:
        u1 = urlparse(pages_urls[0])
        u2 = urlparse(pages_urls[1])
        q1 = parse_qs(u1.query)
        q2 = parse_qs(u2.query)
        
        predictable = True
        for k in q1.keys():
            if k in q2 and q1[k] != q2[k]:
                try:
                    v1 = int(q1[k][0])
                    v2 = int(q2[k][0])
                    if abs(v2 - v1) == 1:
                        dynamic_param_key = k
                        start_page_val = v1
                        continue
                except:
                    predictable = False
                    break
        if predictable and dynamic_param_key:
            strategy = "URL_GENERATION"

    # 4. 汎用セレクタ（リスト抽出ループ）の作成
    def generalize_xpath(xpath_list):
        if len(xpath_list) < 2:
            return xpath_list[0] if xpath_list else ""
        x1 = xpath_list[0].split('/')
        x2 = xpath_list[-1].split('/')
        generalized = []
        for p1, p2 in zip(x1, x2):
            if p1 == p2:
                generalized.append(p1)
            else:
                b1 = re.sub(r'\[\d+\]', '', p1)
                b2 = re.sub(r'\[\d+\]', '', p2)
                if b1 == b2:
                    generalized.append(f"{b1}[{{i}}]")
                else:
                    generalized.append(p1)
        return '/'.join(generalized)
        
    loop_items = [el for el in elements_data if el != next_btn]
    xpaths = [el['xpath'] for el in loop_items]
    generalized_xpath = generalize_xpath(xpaths)
    all_items_xpath = re.sub(r'\[\{i\}\]', '', generalized_xpath or "")

    code_template = f'''import asyncio
from playwright.async_api import async_playwright

class AutoGeneratedScraper:
    def __init__(self):
        self.results = []
        self.seen_data = set() # 重複除外キャッシュ
        self.base_url = "{base_url}"
        
    async def run(self):
        async with async_playwright() as p:
            browser = await p.chromium.launch(headless=False)
            page = await browser.new_page()
            await page.goto(self.base_url)
            
            # 【動的待機】 遷移後の描画完了アンカー
            try:
                await page.wait_for_selector('{wait_anchor_xpath}', state='visible', timeout=10000)
            except:
                pass
                
'''
    if strategy == "URL_GENERATION":
        code_template += f'''
            # 【70点作戦】 パラメータ予測によるURL連番叩き
            page_idx = {start_page_val}
            while True:
                url = self.base_url.replace("{dynamic_param_key}={start_page_val}", f"{dynamic_param_key}={{page_idx}}")
                await page.goto(url)
                
                try:
                    await page.wait_for_selector('{wait_anchor_xpath}', state='visible', timeout=5000)
                except:
                    print("ページ描画タイムアウト。最終ページと判定し終了します。")
                    break
                    
                # 取得する要素がなかったら終了
                count = await page.locator('{all_items_xpath}').count()
                if count == 0:
                    break
                    
                await self.extract_data(page)
                page_idx += 1
'''
    else:
        next_xpath = next_btn['xpath'] if next_btn else None
        code_template += f'''
            # 【安全策】 物理クリック型ページネーション
            while True:
                await self.extract_data(page)
'''
        if next_xpath:
            code_template += f'''
                next_btn = page.locator('{next_xpath}')
                if await next_btn.count() == 0:
                    print("次へボタン消失による終了。")
                    break
                    
                # 【終了判定】 属性変化 (クラス、無効化フラグ等) の厳密判定
                href = await next_btn.get_attribute('href')
                disabled = await next_btn.get_attribute('disabled')
                class_str = await next_btn.get_attribute('class') or ""
                
                if disabled is not None or "disabled" in class_str or (href is None and not class_str):
                    print("次へボタンの非活性化を検知。終了します。")
                    break
                    
                await next_btn.click()
                await page.wait_for_load_state("networkidle")
                try:
                    await page.wait_for_selector('{wait_anchor_xpath}', state='visible', timeout=5000)
                except:
                    pass
'''
        else:
            code_template += f'''
                # ページ送り要素（次へボタン等）が無いためループ終了
                break
'''

    code_template += f'''
            await browser.close()
            return self.results

    async def extract_data(self, page):
        # 汎用セレクタでの抽出
        elements = await page.locator('{all_items_xpath}').all()
        for el in elements:
            text = await el.inner_text()
            text = text.strip()
            if text and text not in self.seen_data:
                self.results.append(text)
                self.seen_data.add(text) # idによる重複除外

if __name__ == "__main__":
    scraper = AutoGeneratedScraper()
    results = asyncio.run(scraper.run())
    print(f"▼ 取得完了: 計 {{len(results)}}件抽出しました ▼")
    # ここで取得した self.results を excel_csv_splitter 等へ手渡すことが可能です
'''
    
    out_path = os.path.join(output_dir, "auto_generated_crawler.py")
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(code_template)

class WebScraperAssistantApp:
    def __init__(self, root):
        self.root = root
        self.root.title("Webスクレイパー支援ツール (記録＆解析)")
        self.root.geometry("450x380")
        self.root.attributes('-topmost', True)

        self.is_recording = False
        self.output_dir = ""
        self.elements_data = []
        
        # スレッド間通信用キュー
        self.cmd_queue = queue.Queue()
        self.event_queue = queue.Queue()

        # GUI要素の配置
        title_label = tk.Label(root, text="Web解析ウォッチャー", font=("Meiryo", 14, "bold"))
        title_label.pack(pady=10)
        
        tk.Label(root, text="操作したいページを開き、\n解析したい要素の上で「Shift + クリック」してください", justify="center").pack(pady=5)

        # メモ入力用UIを追加
        memo_frame = tk.Frame(root)
        memo_frame.pack(fill="x", padx=20, pady=5)
        tk.Label(memo_frame, text="📝 次にクリックする要素のメモ (任意):", font=("Meiryo", 9, "bold")).pack(anchor="w")
        self.memo_var = tk.StringVar()
        tk.Entry(memo_frame, textvariable=self.memo_var, font=("Meiryo", 10), width=40).pack(fill="x", ipady=3)
        tk.Label(memo_frame, text="（例：「次へボタン」「送信者名」と入力してからShift+クリック）", font=("Meiryo", 8), fg="gray").pack(anchor="w")

        self.start_btn = tk.Button(root, text="ブラウザ起動＆記録開始", bg="#4CAF50", fg="white", font=("Meiryo", 11, "bold"), width=30, height=2, command=self.start_browser)
        self.start_btn.pack(pady=10)

        self.status_label = tk.Label(root, text="待機中...", fg="gray")
        self.status_label.pack(pady=5)
        
        # UI更新用の定期チェック
        self.check_events()

    def log(self, msg, color="black"):
        self.status_label.config(text=msg, fg=color)

    def start_browser(self):
        if self.is_recording:
            # 停止リクエストを送信
            self.start_btn.config(state="disabled")
            self.log("停止処理＆データ保存中...", "blue")
            self.cmd_queue.put("STOP")
            return
            
        self.start_btn.config(state="disabled")
        self.log("ブラウザを起動しています...", "blue")
        
        # 保存先フォルダの作成
        desktop_path = os.path.join(os.path.expanduser("~"), "Desktop")
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        self.output_dir = os.path.join(desktop_path, f"Web解析結果_{timestamp}")
        os.makedirs(self.output_dir, exist_ok=True)
        self.elements_data = []
        
        # Playwrightを別スレッドで起動
        threading.Thread(target=playwright_worker, args=(self.cmd_queue, self.event_queue, self.output_dir), daemon=True).start()
        
        self.is_recording = True
        self.start_btn.config(text="記録終了＆データ出力", bg="#f44336")
        self.start_btn.config(state="normal")

    def check_events(self):
        """別スレッドからのメッセージを定期的に確認する"""
        try:
            while True:
                msg = self.event_queue.get_nowait()
                msg_type = msg.get("type")
                
                if msg_type == "log":
                    self.log(msg["text"], msg.get("color", "black"))
                    
                elif msg_type == "element_recorded":
                    # クリックされた瞬間のメモを取得し、次回用にクリアする
                    current_memo = self.memo_var.get()
                    msg["data"]["memo"] = current_memo
                    self.memo_var.set("") # 次の要素のためにリセット
                    
                    self.elements_data.append(msg["data"])
                    self.log(f"{msg['idx']}件目({current_memo or 'メモなし'})のデータを保存しました！", "green")
                    
                elif msg_type == "finished":
                    self.is_recording = False
                    self.start_btn.config(text="ブラウザ起動＆記録開始", bg="#4CAF50", state="normal")
                    self.log("完了しました。", "black")
                    
                    self.page_content = msg.get("page_content", "")
                    
                    if self.elements_data:
                        try:
                            self.export_data()
                            messagebox.showinfo("出力完了", f"データを正常に出力しました！\nデスクトップを確認してください。")
                        except Exception as e:
                            messagebox.showerror("出力エラー", f"ファイル保存中にエラー:\n{e}")
                    else:
                        messagebox.showwarning("データなし", "記録された要素が0件でした。\nブラウザ上でShift+クリックが反応していたか確認してください。")
                        
                elif msg_type == "error":
                    self.is_recording = False
                    self.start_btn.config(text="ブラウザ起動＆記録開始", bg="#4CAF50", state="normal")
                    self.log("エラー発生", "red")
                    messagebox.showerror("Playwrightエラー", msg["error"])
                    
        except queue.Empty:
            pass
            
        # 100msごとに再度チェック
        self.root.after(100, self.check_events)

    def export_data(self):
        # 1. JSON出力
        json_path = os.path.join(self.output_dir, "context.json")
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(self.elements_data, f, ensure_ascii=False, indent=2)
            
        # 2. HTML出力
        html_path = os.path.join(self.output_dir, "report.html")
        html_content = f"""<html>
        <head><meta charset="utf-8"><title>Web抽出レポート</title>
        <style>
            body {{ font-family: sans-serif; background: #f5f5f5; padding: 20px; }}
            .overview {{ background: #fff; padding: 15px; border-radius: 8px; margin-bottom: 30px; border: 2px solid #4CAF50; }}
            .card {{ background: white; border-radius: 8px; padding: 15px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); border-left: 5px solid #2196F3; }}
            img {{ max-width: 100%; border: 1px solid #ccc; margin-top: 10px; }}
            pre {{ background: #272822; color: #f8f8f2; padding: 10px; border-radius: 4px; overflow-x: auto; }}
        </style></head>
        <body>
            <h1>Web構造・要素抽出マップ</h1>
            <div class="overview">
                <h2>【全体マップ】</h2>
                <p>各操作・要素の紐付け番号（マーカー）が配置された画面全体図です。</p>
                <img src="overview_annotated.png" alt="Overall Map">
            </div>
            <h2>【各要素の詳細】</h2>
        """
        
        for item in self.elements_data:
            html_content += f"""
            <div class="card">
                <h2>番号 {item['id']} ({item['tag']})</h2>
                <p><b>URL:</b> {item['url']}</p>
                <p><b>テキスト:</b> {item['text']}</p>
                <p><b>XPath:</b> <code>{item['xpath']}</code></p>
                <h3>HTML構造</h3>
                <pre><code>{item.get('outerHTML', item.get('html_snippet', ''))}</code></pre>
                <h3>要素キャプチャ</h3>
                <img src="{item['target_img']}">
            </div>"""
        html_content += "</body></html>"
        
        with open(html_path, "w", encoding="utf-8") as f:
            f.write(html_content)
            
        # [NEW] AIにそのままコピペして投げられるMarkdown出力
        md_path = os.path.join(self.output_dir, "ai_prompt_context.md")
        md_content = "AIプロンプト用 抽出コンテキストマップ\n=================================\n\n"
        md_content += "【全体マップ】\n生成された `overview_annotated.png` に記載されている番号（1,2,3...）が、以下の要素情報と完全に紐づいています。\n全体HTMLは `full_page_source.html` を参照してください。\n\n"
        md_content += "【要素詳細】\n"
        for item in self.elements_data:
            md_content += f"## 要素番号 {item['id']} ({item['tag']})\n"
            md_content += f"- URL: {item['url']}\n"
            md_content += f"- XPath: `{item['xpath']}`\n"
            md_content += f"- テキスト: {item['text']}\n"
            md_content += "```html\n" + item.get('outerHTML', item.get('html_snippet', '')) + "\n```\n\n"

            
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        # [NEW] 終了時の画面全体のHTMLソースを保存
        if hasattr(self, 'page_content') and self.page_content:
            full_html_path = os.path.join(self.output_dir, "full_page_source.html")
            with open(full_html_path, "w", encoding="utf-8") as f:
                f.write(self.page_content)
            
        # 3. Excel出力 (AIにそのまま丸投げできるよう最適化)
        excel_path = os.path.join(self.output_dir, "elements_list.xlsx")
        wb = openpyxl.Workbook()
        
        # --- 1シート目: 全体概要 ---
        ws_overview = wb.active
        ws_overview.title = "全体概要"
        ws_overview.column_dimensions['A'].width = 100
        ws_overview.column_dimensions['B'].width = 100
        ws_overview.column_dimensions['C'].width = 100
        
        ws_overview.cell(row=1, column=1, value="■ 全体マップ (アノテーション付き)").font = openpyxl.styles.Font(bold=True, size=14)
        overview_img_path = os.path.join(self.output_dir, "overview_annotated.png")
        if os.path.exists(overview_img_path):
            try:
                img = ExcelImage(overview_img_path)
                if img.width > 800:
                    ratio = 800 / img.width
                    img.width = 800
                    img.height = int(img.height * ratio)
                ws_overview.add_image(img, "A3")
            except Exception:
                ws_overview.cell(row=3, column=1, value="※画像を結合できませんでした(Pillow未インストールの可能性)")
                
        ws_overview.cell(row=1, column=2, value="■ 画面全体HTMLソース").font = openpyxl.styles.Font(bold=True, size=14)
        if hasattr(self, 'page_content') and self.page_content:
            html_content = self.page_content
            for i in range(0, len(html_content), 30000):
                ws_overview.cell(row=3+(i//30000), column=2, value=html_content[i:i+30000])
                
        ws_overview.cell(row=1, column=3, value="■ 解析済みJSONデータ").font = openpyxl.styles.Font(bold=True, size=14)
        json_str = json.dumps(self.elements_data, ensure_ascii=False, indent=2)
        for i in range(0, len(json_str), 30000):
            ws_overview.cell(row=3+(i//30000), column=3, value=json_str[i:i+30000])
            
        # --- 2シート目: 要素リスト (画像入り) ---
        ws = wb.create_sheet(title="抽出要素リスト(AIプロンプト用)")
        
        headers = ["番号", "スクリーンショット", "メモ(用途など)", "タグ", "テキスト", "XPath", "HTML構造(OuterHTML)", "ページURL"]
        for col, h in enumerate(headers, 1):
            cell = ws.cell(row=1, column=col, value=h)
            cell.font = openpyxl.styles.Font(bold=True)
            cell.fill = openpyxl.styles.PatternFill(start_color="D9D9D9", end_color="D9D9D9", fill_type="solid")
            
        ws.column_dimensions['B'].width = 30
        ws.column_dimensions['C'].width = 25
        ws.column_dimensions['E'].width = 20
        ws.column_dimensions['F'].width = 45
        ws.column_dimensions['G'].width = 50
        ws.column_dimensions['H'].width = 30
            
        for idx, item in enumerate(self.elements_data, 2):
            ws.row_dimensions[idx].height = 100 # 画像用に高さを確保
            
            ws.cell(row=idx, column=1, value=item["id"])
            
            # スクリーンショットをセルに埋め込む
            img_path = os.path.join(self.output_dir, item["target_img"])
            if os.path.exists(img_path):
                try:
                    img = ExcelImage(img_path)
                    max_height = 120
                    if img.height > max_height:
                        ratio = max_height / img.height
                        img.height = max_height
                        img.width = int(img.width * ratio)
                    ws.add_image(img, f"B{idx}")
                except Exception:
                    ws.cell(row=idx, column=2, value="※画像エラー")
            else:
                ws.cell(row=idx, column=2, value="※画像なし")
                
            ws.cell(row=idx, column=3, value=item.get("memo", ""))
            ws.cell(row=idx, column=4, value=item["tag"])
            ws.cell(row=idx, column=5, value=item["text"])
            ws.cell(row=idx, column=6, value=item["xpath"])
            ws.cell(row=idx, column=7, value=item.get("outerHTML", item.get("html_snippet", "")))
            ws.cell(row=idx, column=8, value=item["url"])
            
        # コードジェネレーターの実行 (Pythonスクリプト自動生成)
        analyze_and_generate_code(self.elements_data, self.output_dir)
        
        messagebox.showinfo("保存完了", f"記録データを保存し、AIクロール用スクリプトを自動生成しました。\n{self.output_dir}")
        self.output_dir = ""


def playwright_worker(cmd_queue, event_queue, output_dir):
    """Playwrightを完全に独立した裏スレッドで動かす（UIのフリーズを回避）"""
    try:
        from playwright.sync_api import sync_playwright
        with sync_playwright() as p:
            edge_path = r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe"
            if os.path.exists(edge_path):
                browser = p.chromium.launch(executable_path=edge_path, headless=False)
            else:
                browser = p.chromium.launch(channel="msedge", headless=False)
                
            context = browser.new_context()
            page = context.new_page()
            
            # 複数フレーム（iframe）対応のため、Python側へ直接データを送るキューと関数を準備
            js_event_queue = queue.Queue()
            js_counter = 0
            counter_lock = threading.Lock()
            
            def get_counter():
                nonlocal js_counter
                with counter_lock:
                    js_counter += 1
                    return js_counter
                    
            def handle_js_data(data):
                js_event_queue.put(data)
                
            context.expose_function("getPythonCounter", get_counter)
            context.expose_function("sendToPython", handle_js_data)
            
            # JavaScriptインジェクション（クリックでデータを抽出し、expose_function経由でフレームの壁を超えて渡す）
            init_script = """
            document.addEventListener('click', async (e) => {
                if (e.shiftKey) {
                    e.preventDefault();
                    e.stopPropagation();
                    
                    const currentId = await window.getPythonCounter();
                    
                    function getXPath(el) {
                        if (el.id) return `//*[@id="${el.id}"]`;
                        if (el === document.body) return el.tagName;
                        let ix = 0;
                        let siblings = el.parentNode.childNodes;
                        for (let i = 0; i < siblings.length; i++) {
                            let sibling = siblings[i];
                            if (sibling === el) return getXPath(el.parentNode) + '/' + el.tagName.toLowerCase() + '[' + (ix + 1) + ']';
                            if (sibling.nodeType === 1 && sibling.tagName === el.tagName) ix++;
                        }
                    }
                    
                    const data = {
                        tag: e.target.tagName,
                        xpath: getXPath(e.target),
                        text: e.target.innerText ? e.target.innerText.substring(0, 50) : "",
                        outerHTML: e.target.outerHTML.substring(0, 500),
                        className: e.target.className && typeof e.target.className === 'string' ? e.target.className : "",
                        href: e.target.getAttribute('href') || (e.target.closest('a') ? e.target.closest('a').getAttribute('href') : ""),
                        disabled: e.target.disabled || e.target.getAttribute('disabled') !== null
                    };
                    
                    // 枠を赤く光らせる（一時的）
                    const oldBorder = e.target.style.outline;
                    e.target.style.outline = "4px solid red";
                    setTimeout(() => { e.target.style.outline = oldBorder; }, 500);
                    
                    // 画面上に消えない番号「バッジ」を残す
                    const badge = document.createElement('div');
                    badge.textContent = currentId;
                    badge.style.position = 'absolute';
                    badge.style.left = e.pageX + 'px';
                    badge.style.top = e.pageY + 'px';
                    badge.style.transform = 'translate(-50%, -50%)'; // 中心配置
                    badge.style.backgroundColor = '#e53935';
                    badge.style.color = 'white';
                    badge.style.borderRadius = '50%';
                    badge.style.width = '30px';
                    badge.style.height = '30px';
                    badge.style.display = 'flex';
                    badge.style.alignItems = 'center';
                    badge.style.justifyContent = 'center';
                    badge.style.fontWeight = 'bold';
                    badge.style.fontSize = '16px';
                    badge.style.zIndex = '999999';
                    badge.style.border = '3px solid white';
                    badge.style.boxShadow = '0 3px 6px rgba(0,0,0,0.3)';
                    badge.style.pointerEvents = 'none'; // クリックの妨げにならないよう
                    document.body.appendChild(badge);
                    
                    window.sendToPython({ data: data, id: currentId });
                }
            }, true);
            """
            context.add_init_script(init_script)
            page.goto("https://www.google.com/")
            event_queue.put({"type": "log", "text": "記録中: 対象上で Shift+クリック", "color": "red"})
            
            element_count = 0
            page_content = ""
            
            while True:
                # 終了リクエストの確認
                try:
                    cmd = cmd_queue.get_nowait()
                    if cmd == "STOP":
                        try:
                            # 終了時点のページ全体のHTMLを取得して最終保存
                            page_content = page.content()
                            
                            # これまでクリックした全番号バッジが乗った「全体マップ」を撮影
                            overview_img_path = os.path.join(output_dir, "overview_annotated.png")
                            page.screenshot(path=overview_img_path, full_page=True)
                        except:
                            pass
                        break
                except queue.Empty:
                    pass
                    
                # iframeの壁を超えたキューから要素を取得
                try:
                    while True:
                        payload = js_event_queue.get_nowait()
                        data = payload["data"]
                        idx = payload["id"]
                        
                        event_queue.put({"type": "log", "text": f"画像撮影中: {data['tag']}", "color": "blue"})
                        
                        full_img_name = f"step{idx}_full.png"
                        full_img_path = os.path.join(output_dir, full_img_name)
                        page.screenshot(path=full_img_path)
                        
                        target_img_name = f"step{idx}_target.png"
                        target_img_path = os.path.join(output_dir, target_img_name)
                        try:
                            page.locator(f"xpath={data['xpath']}").screenshot(path=target_img_path)
                        except Exception:
                            target_img_name = full_img_name
                            
                        data["id"] = idx
                        data["url"] = page.url
                        data["full_img"] = full_img_name
                        data["target_img"] = target_img_name
                        
                        event_queue.put({"type": "element_recorded", "data": data, "idx": idx})
                except queue.Empty:
                    pass
                    
                time.sleep(0.1)
                
            browser.close()
            event_queue.put({"type": "finished", "page_content": page_content})
            
    except Exception as e:
        event_queue.put({"type": "error", "error": str(e)})

if __name__ == "__main__":
    root = tk.Tk()
    app = WebScraperAssistantApp(root)
    root.mainloop()
